logging:
  level: INFO
  loggers:
    io.jegutierrez: INFO

# app config
template: Hello, %s!
defaultName: Stranger

# server config
server:
  applicationConnectors:
    - type: http
      port: 8080
    - type: https
      port: 8443
      keyStorePath: data-keeper.keystore
      keyStorePassword: data-keeper
      validateCerts: false