logging:
  level: INFO
  loggers:
    io.jegutierrez: INFO

# app config
nodeName: node1.io
zooKeeperAddress: localhost
zooKeeperPort: 2181
zooKeeperTimeout: 5000

# server config
server:
  applicationConnectors:
    - type: http
      port: 8080
    # - type: https
    #   port: 8443
    #   keyStorePath: data-keeper.keystore
    #   keyStorePassword: data-keeper
    #   validateCerts: false
  adminConnectors:
    - type: http
      port: 8081